name: Deploy github pages

on:
  push:
    branches:
      - APICS-2325_automatise_gh_pages_deploy

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.15.3]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          persist-credentials: false
      - name: npm install 
        run: npm i
      - name: deploy
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
          git config --global user.email "bilal.kabat@vonage.com"
          git config --global user.name "bilalkabat"
          npm run deploy
